=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/AbstractDocument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.processpuzzle.com/SmartDocument"
  targetNamespace="http://www.processpuzzle.com/SmartDocument"
  elementFormDefault="qualified">

  <xs:element name="abstractDocumentDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="version"/>
        <xs:element ref="contentUri"/>
        <xs:element ref="handleMenuSelectedEvents"/>
        <xs:element ref="resources"/>
      </xs:sequence>
    </xs:complexType>

  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="version" type="xs:decimal"/>
  <xs:element name="contentUri" type="xs:string"/>
  <xs:element name="handleMenuSelectedEvents" type="xs:boolean"/>
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="styleSheets"/>
        <xs:element ref="images"/>
        <xs:element ref="javaScripts"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="styleSheets">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="styleSheet" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="styleSheet" type="xs:anyURI"/>

  <xs:element name="images">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="image" type="xs:anyURI"/>

  <xs:element name="javaScripts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="javaScript" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="javaScript" type="xs:anyURI"/>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/ResourceManager/TestResourcesDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:abstractDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/AbstractDocument.xsd">
   <sd:name>Test Smart Document</sd:name>
   <sd:description>This configuration supports testing Smart Document.</sd:description>
   <sd:version>0.5</sd:version>
   
   <sd:resources>
      <sd:styleSheets>
         <sd:styleSheet>../ResourceManager/DummyCSS.css</sd:styleSheet>
      </sd:styleSheets>

      <sd:images>
         <sd:image id="logoImage" title="ProcessPuzzle">../SmartDocument/Images/ProcessPuzzleLogo.jpg</sd:image>
      </sd:images>
      
      <sd:javaScripts>
         <sd:javaScript>../ResourceManager/DummyScript.js</sd:javaScript>
         <sd:javaScript>../../Source/LanguageSelectorWidget/LanguageChangedMessage.js</sd:javaScript>
      </sd:javaScripts>
   </sd:resources>
</sd:abstractDocumentDefinition>
