=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/MenuDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.processpuzzle.com/MenuDefinition"
  targetNamespace="http://www.processpuzzle.com/MenuDefinition"
  elementFormDefault="qualified">
  
  <xs:element name="menuDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="menuItem" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="menuItem">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="menuItem"/>
        <xs:element ref="messageProperties"/>
      </xs:choice>
      <xs:attribute name="caption" type="xs:NCName"/>
      <xs:attribute name="isDefault" type="xs:boolean"/>
      <xs:attribute name="menuItemId" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="messageProperties" type="xs:string"/>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/WidgetExamples/MenuDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<md:menuDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:md="http://www.processpuzzle.com/MenuDefinition"
   xsi:schemaLocation="http://www.processpuzzle.com/MenuDefinition http://processpuzzle.com/Schemas/MenuDefinition.xsd">
	
	<md:menuItem menuItemId="MenuWidget">
      <md:menuItem menuItemId="YourMenu" caption="WebUIMenu.documentExamples" isDefault="true">
               
         <md:menuItem menuItemId="YourMenu-Html" caption="WebUIMenu.documentExamples.htmlContent" isDefault="true">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/HtmlDocument.xml', documentType : AbstractDocument.Types.HTML }</pp:messageProperties>         
         </md:menuItem>       
               
         <md:menuItem menuItemId="YourMenu-Static" caption="WebUIMenu.documentExamples.staticDocument" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/StaticDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>       
               
         <md:menuItem menuItemId="YourMenu-Dynamic" caption="WebUIMenu.documentExamples.dynamicDocument" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/DynamicDocument.xml', documentContentURI : 'Content/DynamicContent', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
         
         <md:menuItem menuItemId="YourMenu-PhotoAlbum" caption="WebUIMenu.documentExamples.photoAlbum" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/PhotoGaleryDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
         
         <md:menuItem menuItemId="YourMenu-VideoAlbum" caption="WebUIMenu.documentExamples.videoAlbum" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/VideoGaleryDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>       
         
         <md:menuItem menuItemId="YourMenu-Diagram" caption="WebUIMenu.documentExamples.diagram" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/WidgetExamples/DiagramDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
      </md:menuItem>
      
      <md:menuItem menuItemId="Widgets" caption="WebUIMenu.widgets">
               
         <md:menuItem menuItemId="Widgets-HierachicalMenuWidget" caption="WebUIMenu.widgets.menuWidget" isDefault="true">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/WidgetExamples/HierarchicalMenuWidgetDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
               
         <md:menuItem menuItemId="Widgets-NewsReader" caption="WebUIMenu.widgets.newsReader" isDefault="false">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/WidgetExamples/DiagramDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
                  
         <md:menuItem menuItemId="Widgets-Event" caption="WebUIMenu.widgets.eventsReader">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/WidgetExamples/DiagramDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
                  
         <md:menuItem menuItemId="Widgets-Tree" caption="WebUIMenu.widgets.treeView">
            <pp:messageProperties>{ activityType : AbstractDocument.Activity.LOAD_DOCUMENT, documentURI : 'Content/WidgetExamples/TreeDocument.xml', documentType : AbstractDocument.Types.SMART }</pp:messageProperties>         
         </md:menuItem>
      </md:menuItem>
	</md:menuItem>
</md:menuDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/HierarchicalMenuWidget/MenuDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<md:menuDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:md="http://www.processpuzzle.com/MenuDefinition"
	xsi:schemaLocation="http://www.processpuzzle.com/MenuDefinition http://processpuzzle.com/Schemas/MenuDefinition.xsd">
	
	<md:menuItem menuItemId="MenuWidget">
		<md:menuItem menuItemId="mainItemOne" caption="HierarchicalMenuWidget.mainItemOne" isDefault="true">
			<md:messageProperties>{actionType : 'loadMenu'}</md:messageProperties>			
				
			<md:menuItem menuItemId="itemOneOfOne" caption="HierarchicalMenuWidget.itemOne" isDefault="true">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentOne'}</md:messageProperties>			
			</md:menuItem>
			
			<md:menuItem menuItemId="itemTwoOfOne" caption="HierarchicalMenuWidget.itemTwo">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentTwo'}</md:messageProperties>
			</md:menuItem>
			
			<md:menuItem menuItemId="itemThreeOfOne" caption="HierarchicalMenuWidget.itemThree">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentThree'}</md:messageProperties>
			</md:menuItem>
		</md:menuItem>
		
		<md:menuItem menuItemId="mainItemTwo" caption="HierarchicalMenuWidget.mainItemTwo" isDefault="true">
			<md:messageProperties>{actionType : 'loadMenu'}</md:messageProperties>			
				
			<md:menuItem menuItemId="itemOneOfTwo" caption="HierarchicalMenuWidget.itemOne">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentOne'}</md:messageProperties>			
			</md:menuItem>
			
			<md:menuItem menuItemId="itemTwoOfTwo" caption="HierarchicalMenuWidget.itemTwo" isDefault="true">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentTwo'}</md:messageProperties>
			</md:menuItem>
			
			<md:menuItem menuItemId="itemThreeOfTwo" caption="HierarchicalMenuWidget.itemThree">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentThree'}</md:messageProperties>
			</md:menuItem>
		</md:menuItem>
		
		<md:menuItem menuItemId="mainItemThree" caption="HierarchicalMenuWidget.mainItemThree">
			<md:messageProperties>{actionType : 'loadMenu'}</md:messageProperties>			
				
			<md:menuItem menuItemId="itemOneOfThree" caption="HierarchicalMenuWidget.itemOne">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentOne'}</md:messageProperties>			
			</md:menuItem>
			
			<md:menuItem menuItemId="itemTwoOfThree" caption="HierarchicalMenuWidget.itemTwo">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentTwo'}</md:messageProperties>
			</md:menuItem>
			
			<md:menuItem menuItemId="itemThreeOfThree" caption="HierarchicalMenuWidget.itemThree" isDefault="true">
				<md:messageProperties>{actionType : 'loadDocument', documentURI : 'Content/SampleContentThree'}</md:messageProperties>
			</md:menuItem>
		</md:menuItem>
	</md:menuItem>
</md:menuDefinition>
