=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/PartyNews.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.processpuzzle.com/PartyNews"
  targetNamespace="http://www.processpuzzle.com/PartyNews"
  elementFormDefault="qualified">

  <xs:element name="rss">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="channel"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="channel">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="link"/>
        <xs:element ref="description"/>
        <xs:element ref="language"/>
        <xs:element ref="pubDate"/>
        <xs:element ref="lastBuildDate"/>
        <xs:element ref="docs"/>
        <xs:element ref="generator"/>
        <xs:element ref="managingEditor"/>
        <xs:element ref="webMaster"/>
        <xs:element maxOccurs="unbounded" ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="language" type="xs:NCName"/>
  <xs:element name="lastBuildDate" type="xs:string"/>
  <xs:element name="docs" type="xs:anyURI"/>
  <xs:element name="generator" type="xs:string"/>
  <xs:element name="managingEditor" type="xs:string"/>
  <xs:element name="webMaster" type="xs:string"/>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="link"/>
        <xs:element ref="description"/>
        <xs:element ref="pubDate"/>
        <xs:element ref="guid"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute name="href" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="guid" type="xs:anyURI"/>
  <xs:element name="link" type="xs:anyURI"/>
  <xs:element name="pubDate" type="xs:string"/>

  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any namespace="http://www.w3.org/1999/xhtml" processContents="lax" />
      </xs:choice>
      <xs:attribute name="href" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/DynamicContent_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<pn:rss version="2.0" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pn="http://www.processpuzzle.com/PartyNews"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyNews http://processpuzzle.com/Schemas/PartyNews.xsd">
  <pn:channel>
    <pn:title>ProcessPuzzle</pn:title>
    <pn:link>http://processpuzzle.com</pn:link>
    <pn:description>ProcessPuzzle company news</pn:description>
    <pn:language>en-us</pn:language>
    <pn:pubDate>Tue, 10 Jun 2003 04:00:00 GMT</pn:pubDate>
    <pn:lastBuildDate>Tue, 10 Jun 2003 09:41:01 GMT</pn:lastBuildDate>
    <pn:docs>http://processpuzzle.com/rss</pn:docs>
    <pn:generator>ProcessPuzzle RSS Generator 2.0</pn:generator>
    <pn:managingEditor>Zsolt Zsuffa, zsolt.zsuffa@example.com</pn:managingEditor>
    <pn:webMaster>Peter Krima, peter.krima@example.com</pn:webMaster>    
    
    <pn:item>
		<pn:title>HONNIA furniture design service lunched</pn:title>
		<pn:link>http://honnia.hu/news</pn:link>
		<pn:description>Cerasus Llc. lunched a new woldwide available furniture design service based on ProcessPuzzle.</pn:description>
		<pn:pubDate>Tue, 03 Jun 2003 09:39:21 GMT</pn:pubDate>
		<pn:guid>http://processpuzzle.com#item573</pn:guid>
    </pn:item>  
    
    <pn:item>
		<pn:title>ProcessPuzzle NewsReaderWidget is ready to use</pn:title>
		<pn:link>http://processpuzzle.com/news</pn:link>
		<pn:description>IT Codex Llc. released a new browser wiget for it's well known ProcessPuzzle framework.</pn:description>
		<pn:pubDate>Tue, 03 Jun 2003 09:39:21 GMT</pn:pubDate>
		<pn:guid>http://processpuzzle.com#item575</pn:guid>
    </pn:item>  
  </pn:channel>  
</pn:rss>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/WidgetExamples/SiteNews_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<pn:rss version="2.0" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pn="http://www.processpuzzle.com/PartyNews"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyNews http://processpuzzle.com/Schemas/PartyNews.xsd">
   <pn:channel>
      <pn:title>ProcessPuzzle</pn:title>
      <pn:link>http://processpuzzle.com</pn:link>
      <pn:description>ProcessPuzzle company news.</pn:description>
      <pn:language>en-us</pn:language>
      <pn:pubDate>Tue, 10 Jun 2003 04:00:00 GMT</pn:pubDate>
      <pn:lastBuildDate>Tue, 10 Jun 2003 09:41:01 GMT</pn:lastBuildDate>
      <pn:docs>http://processpuzzle.com/rss</pn:docs>
      <pn:generator>Weblog Editor 2.0</pn:generator>
      <pn:managingEditor>zsolt.zsuffa@example.com</pn:managingEditor>
      <pn:webMaster>peter.krima@example.com</pn:webMaster>    
    
      <pn:item>
         <pn:title>HONNIA furniture design service lunched</pn:title>
         <pn:link>Content/WidgetExamples/NewsDetail.xml?contentUri='Content/WidgetExamples/SiteNews.xml'&amp;documentVariables={index:'1'}&amp;documentType=SMART</pn:link>
         <pn:description>Cerasus Llc. launched a new worldwide available furniture design service based on ProcessPuzzle. Design your own furniture, exactly in a style which fits into you existing furnitures, specify size accomodates to your room.</pn:description>
         <pn:pubDate>Tue, 03 Jun 2003 09:39:21 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item573</pn:guid>
      </pn:item>  
    
      <pn:item>
         <pn:title>ProcessPuzzle NewsReaderWidget is ready to use</pn:title>
         <pn:link>Content/WidgetExamples/NewsDetail.xml?contentUri='Content/WidgetExamples/SiteNews.xml'&amp;documentVariables={index:'2'}&amp;documentType=SMART</pn:link>
         <pn:description>IT Codex Llc. released a new browser wiget for it's well known ProcessPuzzle framework. NewsReaderWidget displays RSS feed in a customizable way and can be embedded into any SmartDocument.</pn:description>
         <pn:pubDate>Tue, 03 Jun 2003 09:39:21 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item575</pn:guid>
      </pn:item>  
  </pn:channel>  
</pn:rss>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/NewsReaderWidget/TestNews_hu.xml
<?xml version="1.0" encoding="UTF-8"?>
<pn:rss version="2.0" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pn="http://www.processpuzzle.com/PartyNews"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyNews http://processpuzzle.com/Schemas/PartyNews.xsd">
   <pn:channel>
      <pn:title>ProcessPuzzle</pn:title>
      <pn:link>http://processpuzzle.com</pn:link>
      <pn:description>ProcessPuzzle friss híre.</pn:description>
      <pn:language>hu-hu</pn:language>
      <pn:pubDate>Tue, 10 Jun 2003 04:00:00 GMT</pn:pubDate>
      <pn:lastBuildDate>Tue, 10 Jun 2003 04:00:00 GMT</pn:lastBuildDate>
      <pn:docs>http://processpuzzle.com/rss</pn:docs>
      <pn:generator>Weblog Editor 2.0</pn:generator>
      <pn:managingEditor>zsolt.zsuffa@example.com</pn:managingEditor>
      <pn:webMaster>peter.krima@example.com</pn:webMaster>    
    
      <pn:item>
         <pn:title>HONNIA bútor tervezés</pn:title>
         <pn:link>http://honnia.hu/news</pn:link>
         <pn:description>Cerasus Kft. elindította új, a ProcessPuzzle üzleti platformra épülő, világszerte elérhető Internetes szolgáltatását. A Honniával postosan a saját stílusában tervezheti meg bútotát, éppen az adottságainak megfelelő méretben.</pn:description>
         <pn:pubDate>Tue, 10 Jun 2003 04:00:00 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item573</pn:guid>
      </pn:item>  
    
      <pn:item>
         <pn:title>ProcessPuzzle hírolvasó komponens</pn:title>
         <pn:link>Content/WidgetExamples/UpcommingEvents.xml</pn:link>
         <pn:description>IT Kódex Kft. új felhasználói felület komponenst fejlesztett ki az RSS hírcsatornák megjelenítésére. A NewsReaderWidget a híreket testre szabható módon jeleníti meg és bármely okos dokumentumba beépíthető.</pn:description>
         <pn:pubDate>Tue, 03 Jun 2003 09:39:21 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item575</pn:guid>
      </pn:item>  
  </pn:channel>  
</pn:rss>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/System/Facebook_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<pn:rss version="2.0" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pn="http://www.processpuzzle.com/PartyNews"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyNews http://processpuzzle.com/Schemas/PartyNews.xsd">
   <pn:channel>
      <pn:title>Facebook Message Wall</pn:title>
      <pn:link>https://www.facebook.com/groups/processpuzzle/</pn:link>
      <pn:description>ProcessPuzzle - Facebook group</pn:description>
      <pn:language>hu-HU</pn:language>
      <pn:pubDate>Mon, 13 March 2012, 04:00:00 GMT</pn:pubDate>
      <pn:lastBuildDate>Mon, 13 March 2012, 04:00:00 GMT</pn:lastBuildDate>
      <pn:docs>https://www.facebook.com/groups/processpuzzle/rss</pn:docs>
      <pn:generator>Weblog Editor 2.0</pn:generator>
      <pn:managingEditor>zsolt.zsuffa@itkodex.hu</pn:managingEditor>
      <pn:webMaster>peter.krima@itkodex.hu</pn:webMaster>    
    
      <pn:item>
         <pn:title>Ákos Várhegyi joined to ProcessPuzzle team</pn:title>
         <pn:link>https://www.facebook.com/groups/processpuzzle</pn:link>
         <pn:description>
            With he's 20 years experience in complex system design he'll be strengthen the ProcessPuzzle Consultans group. He'll also lunch ProcessPuzzle Advisor Partner Program.
         </pn:description>
         <pn:pubDate>Mon, 05 March 2012, 09:39:21 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item575</pn:guid>
      </pn:item>  
      
      <pn:item>
         <pn:title>Usability question: Toggle between edit and view mode makes sense?</pn:title>
         <pn:link>https://www.facebook.com/groups/processpuzzle/</pn:link>
         <pn:description>
            ProcessPuzzle follows the "Edit in-place if you're authorized." usability rule. There is no administrative UI, special UI for content management or workflow specification. 
            Consequently if you add a link to a TextElement of SmartDocument this link will work. This behavior seems to be logical, in the other hand clicking on link can navigate the user to another site. Can this harm the user?
            Does it makes sense to provide view and edit mode? (supposed the user is authorized)
         </pn:description>
         <pn:pubDate>Mon, 05 March 2012, 09:39:21 GMT</pn:pubDate>
         <pn:guid>http://processpuzzle.com#item575</pn:guid>
      </pn:item>  
  </pn:channel>  
</pn:rss>
