=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/PartyEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.processpuzzle.com/PartyEvent"
  targetNamespace="http://www.processpuzzle.com/PartyEvent"
  elementFormDefault="qualified">

  <xs:element name="eventList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="events" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="events">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="event"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="link"/>
        <xs:element ref="description"/>
        <xs:element ref="program"/>
        <xs:element ref="schedule"/>
        <xs:element ref="location"/>
        <xs:element ref="language"/>
        <xs:element ref="registration"/>
        <xs:element ref="publicationDate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:attribute name="href" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="program">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="startDate"/>
        <xs:element ref="endDate"/>
        <xs:element ref="recurrence"/>
      </xs:sequence>
      <xs:attribute name="isFullDay" use="required" type="xs:NCName"/>
      <xs:attribute name="isMultipleDay" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="startDate" type="xs:string"/>
  <xs:element name="endDate" type="xs:string"/>
  <xs:element name="recurrence" type="xs:string"/>

  <xs:element name="location">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="address"/>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="address">
    <xs:complexType mixed="true">
      <xs:attribute name="href" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="language" type="xs:NCName"/>

  <xs:element name="registration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="publicationDate" type="xs:string"/>

  <xs:element name="link">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:anyURI">
          <xs:attribute name="href" type="xs:anyURI"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any namespace="http://www.w3.org/1999/xhtml" processContents="lax" />
      </xs:choice>
      <xs:attribute name="href"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/WidgetExamples/UpcommingEvents_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<pe:eventList 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns="http://www.w3.org/1999/xhtml" 
   xmlns:pe="http://www.processpuzzle.com/PartyEvent"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyEvent http://processpuzzle.com/Schemas/PartyEvent.xsd">
      
   <pe:events>
      <pe:event>
         <pe:title>Unit Test Driven JavaScript Development - Training</pe:title>
         <pe:link>Content/WidgetExamples/EventDetail.xml?contentUri='Content/WidgetExamples/UpcommingEvents.xml'&amp;documentVariables={index:'1'}&amp;documentType=SMART</pe:link>
         <pe:description>Introduction to Test Driven Development for JavaScript developers.</pe:description>
         <pe:program>
            <pe:description href="Content/DynamicDocument.xml?contentUri='Content/DynamicContent.xml'&amp;documentType=SMART">Detailed agenda</pe:description>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'en'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
         <pe:schedule isFullDay="false">
            <pe:startDate>Tue, 10 Jun 2003 04:00:00 GMT</pe:startDate>
            <pe:endDate>Tue, 10 Jun 2003 08:00:00 GMT</pe:endDate>
         </pe:schedule>
         <pe:location>
            <pe:address>Prof. Agile - virtual classroom</pe:address>
            <pe:link>http://agilerenovation.com</pe:link>
         </pe:location>
         <pe:language>English</pe:language>
         <pe:registration>
            <pe:link href="http://processpuzzle.eventbrite.com/">http://processpuzzle.eventbrite.com/</pe:link>
         </pe:registration>
         <pe:publicationDate>Tue, 10 Jun 2003 04:00:00 GMT</pe:publicationDate>
      </pe:event>  
       
      <pe:event>
         <pe:title>Acceptance Test Driven Java Development - Training</pe:title>
         <pe:link>Content/WidgetExamples/EventDetail.xml?contentUri='Content/WidgetExamples/UpcommingEvents.xml'&amp;documentVariables={index:'2'}&amp;documentType=SMART</pe:link>
         <pe:description>Introduction to Acceptance Test Driven Development for Java developers.</pe:description>
         <pe:program>
            <pe:description href="Content/DynamicDocument.xml?contentUri='Content/DynamicContent.xml'&amp;documentType=SMART">Detailed agenda</pe:description>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'en'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
         <pe:schedule isFullDay="false">
            <pe:startDate></pe:startDate>
            <pe:endDate></pe:endDate>
         </pe:schedule>
         <pe:location>
            <pe:address>Prof. Agile - virtual classroom</pe:address>
            <pe:link>http://agilerenovation.com</pe:link>
         </pe:location>
         <pe:language>English</pe:language>
         <pe:registration>
            <pe:link href="http://processpuzzle.eventbrite.com/">http://processpuzzle.eventbrite.com/</pe:link>
         </pe:registration>
         <pe:publicationDate>Tue, 03 Jun 2003 09:39:21 GMT</pe:publicationDate>
      </pe:event>  
   </pe:events> 
</pe:eventList>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/PartyEventWidget/TestEvents_hu.xml
<?xml version="1.0" encoding="UTF-8"?>
<pe:eventList 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://www.w3.org/1999/xhtml" 
   xmlns:pp="http://www.processpuzzle.com"
   xmlns:pe="http://www.processpuzzle.com/PartyEvent"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyEvent http://processpuzzle.com/Schemas/PartyEvent.xsd">
   
   <pe:events>
	   <pe:event>
	      <pe:title>Egység teszt központú JavaScript fejlesztés - Tanfolyam</pe:title>
	      <pe:link>http://honnia.hu/news</pe:link>
	      <pe:description>Bevezetés az egység teszt alapú fejlesztésbe JavaScript fejlesztők számára.</pe:description>
         <pe:program>
            <pe:description>Részletes program.</pe:description>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'hu'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
	      <pe:schedule isFullDay="false">
	         <pe:startDate></pe:startDate>
	         <pe:endDate></pe:endDate>
	      </pe:schedule>
	      <pe:location>
	         <pe:address>Prof. Agile - virtuális osztályterem</pe:address>
	         <pe:link>http://agilerenovation.com</pe:link>
	      </pe:location>
         <pe:language>magyar</pe:language>
         <pe:registration>
            <pe:link>http://agilerenovation.eventbrite.com/</pe:link>
         </pe:registration>
	      <pe:publicationDate>Tue, 10 Jun 2003 04:00:00 GMT</pe:publicationDate>
	   </pe:event>  
	    
	   <pe:event>
	      <pe:title>Egység teszt központú Java fejlesztés - Tanfolyam</pe:title>
	      <pe:link>Content/WidgetExamples/UpcommingEvents.xml</pe:link>
	      <pe:description>Bevezetés az egység teszt alapú fejlesztésbe Java fejlesztők számára.</pe:description>
         <pe:program>
            <pe:description>Részletes program.</pe:description>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'hu'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
	      <pe:schedule isFullDay="false">
	         <pe:startDate></pe:startDate>
	         <pe:endDate></pe:endDate>
	      </pe:schedule>
	      <pe:location>
	         <pe:address>Prof. Agile - virtuális osztályterem</pe:address>
	         <pe:link>http://agilerenovation.com</pe:link>
	      </pe:location>
         <pe:language>angol</pe:language>
         <pe:registration>
            <pe:link>http://agilerenovation.eventbrite.com/</pe:link>
         </pe:registration>
	      <pe:publicationDate>Tue, 03 Jun 2003 09:39:21 GMT</pe:publicationDate>
	   </pe:event>  
   </pe:events> 
</pe:eventList>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/PartyEventWidget/TestEvents_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<pe:eventList 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns="http://www.w3.org/1999/xhtml" 
   xmlns:pe="http://www.processpuzzle.com/PartyEvent"
   xsi:schemaLocation="http://www.processpuzzle.com/PartyEvent http://processpuzzle.com/Schemas/PartyEvent.xsd">
   
   <pe:events>
      <pe:event>
         <pe:title>Unit Test Driven JavaScript Development - Training</pe:title>
         <pe:link>http://honnia.hu/news</pe:link>
         <pe:description>Introduction to Test Driven Development for JavaScript developers.</pe:description>
         <pe:program>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'hu'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
         <pe:schedule isFullDay="false">
            <pe:startDate>Tue, 10 Jun 2003 04:00:00 GMT</pe:startDate>
            <pe:endDate>Tue, 10 Jun 2003 08:00:00 GMT</pe:endDate>
         </pe:schedule>
         <pe:location>
            <pe:address>Prof. Agile - virtual classroom</pe:address>
            <pe:link>http://agilerenovation.com</pe:link>
         </pe:location>
         <pe:language>English</pe:language>
         <pe:registration>
            <pe:link>http://agilerenovation.eventbrite.com/</pe:link>
         </pe:registration>
         <pe:publicationDate>Tue, 10 Jun 2003 04:00:00 GMT</pe:publicationDate>
      </pe:event>  
       
      <pe:event>
         <pe:title>Unit Test Driven Java Development - Training</pe:title>
         <pe:link>Content/WidgetExamples/UpcommingEvents.xml</pe:link>
         <pe:description>Introduction to Test Driven Development for Java developers.</pe:description>
         <pe:program>
            <pe:link>http://processpuzzle.com/#!WebUIController: {locale: 'hu'}; communityTabs: {currentTabId: 'tab_CommunityTab.faceBook'}; consoleTabs: {currentTabId: 'tab_ConsoleTab.comments'}; verticalMenuColumn: {currentItemId: 'Development-BeginnersTrainings', contextItemId: 'Development'}; horizontalMenuBar: {currentItemId: 'Development', contextItemId: 'MenuWidget'}</pe:link>
         </pe:program>
         <pe:schedule isFullDay="false">
            <pe:startDate></pe:startDate>
            <pe:endDate></pe:endDate>
         </pe:schedule>
         <pe:location>
            <pe:address>Prof. Agile - virtual classroom</pe:address>
            <pe:link>http://agilerenovation.com</pe:link>
         </pe:location>
         <pe:language>Hungarian</pe:language>
         <pe:registration>
            <pe:link>http://agilerenovation.eventbrite.com/</pe:link>
         </pe:registration>
         <pe:publicationDate>Tue, 03 Jun 2003 09:39:21 GMT</pe:publicationDate>
      </pe:event>  
   </pe:events> 
</pe:eventList>
