=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/PhotoGaleryWidgetDefinition.xsd
<?xml version="1.0"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.processpuzzle.com/SmartDocument"
  targetNamespace="http://www.processpuzzle.com/SmartDocument"
  elementFormDefault="qualified">

  <xs:include schemaLocation="AbstractDocument.xsd"/>
  <xs:include schemaLocation="WidgetDefinition.xsd"/>

  <xs:element name="photoGaleryWidgetDefinition">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="WidgetDefinition">
		  <xs:sequence>
		  	<xs:element name="properties" type="Properties" />
		  </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Properties">
    <xs:sequence>
	  <xs:element name="accessKeys" type="xs:string" minOccurs="0" maxOccurs="1" />
	  <xs:element name="automaticallyLinkSlideToFullSizedImage" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="centerImages" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="effectDuration" type="xs:integer" minOccurs="0" maxOccurs="1" />
	  <xs:element name="firstSlide" type="xs:integer" minOccurs="0" maxOccurs="1" />
	  <xs:element name="galeryLink" type="xs:anyURI" minOccurs="0" maxOccurs="1" />
	  <xs:element name="height" type="xs:integer" minOccurs="0" maxOccurs="1" />
	  <xs:element name="imageFolderUri" type="xs:anyURI" minOccurs="0" maxOccurs="1" />
	  <xs:element name="loopShow" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="overlapImages" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="resizeImages" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="showController" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="showImageCaptions" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="showSlidesRandom" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="showThumbnails" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="skipTransition" type="xs:string" minOccurs="0" maxOccurs="1" />
	  <xs:element name="slideChangeDelay" type="xs:integer" minOccurs="0" maxOccurs="1" />
	  <xs:element name="slideTransition" type="xs:string" minOccurs="0" maxOccurs="1" />
	  <xs:element name="startPaused" type="xs:boolean" minOccurs="0" maxOccurs="1" />
	  <xs:element name="thumbnailFileNameRule" type="xs:string" minOccurs="0" maxOccurs="1" />
	  <xs:element name="width" type="xs:integer" minOccurs="0" maxOccurs="1" />
	</xs:sequence>
  </xs:complexType>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/MediaPlayerWidget/SlideShow/SlideShowDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:photoGaleryWidgetDefinition
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:pp="http://www.processpuzzle.com"
   xmlns:sd="http://www.processpuzzle.com/SmartDocument"
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/PhotoGaleryWidgetDefinition.xsd">
   
   <sd:name>PhotoGalery</sd:name>
   <sd:description>Photo Galery presents a set of images, and their thumb nails.</sd:description>
   <sd:version>1.0</sd:version>
   <sd:options></sd:options>
   
   <sd:properties>
      <sd:accessKeys>shift+h</sd:accessKeys>
      <sd:automaticallyLinkSlideToFullSizedImage>true</sd:automaticallyLinkSlideToFullSizedImage>
      <sd:centerImages>true</sd:centerImages>
      <sd:effectDuration>1500</sd:effectDuration>
      <sd:firstSlide>7</sd:firstSlide>
      <sd:galeryLink>http://www.tourism-costarica.com</sd:galeryLink>
      <sd:height>300</sd:height>
      <sd:imageFolderUri>../PhotoGaleryWidget/Album</sd:imageFolderUri>
      <sd:loopShow>true</sd:loopShow>
      <sd:overlapImages>true</sd:overlapImages>
      <sd:resizeImages>true</sd:resizeImages>
      <sd:showController>true</sd:showController>
      <sd:showImageCaptions>true</sd:showImageCaptions>
      <sd:showSlidesRandom>true</sd:showSlidesRandom>
      <sd:showThumbnails>true</sd:showThumbnails>
      <sd:skipTransition>WhenPaused | OnStart</sd:skipTransition>
      <sd:slideChangeDelay>3000</sd:slideChangeDelay>
      <sd:slideTransition>elastic:in:out</sd:slideTransition>
      <sd:thumbnailFileNameRule>[/(\.[^\.]+)$/, '_thumb$1']</sd:thumbnailFileNameRule>
      <sd:width>450</sd:width>
   </sd:properties>
</sd:photoGaleryWidgetDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/PhotoGaleryDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:photoGaleryWidgetDefinition
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:pp="http://www.processpuzzle.com"
   xmlns:sd="http://www.processpuzzle.com/SmartDocument"
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/PhotoGaleryWidgetDefinition.xsd">
   
   <sd:name>PhotoGalery</sd:name>
   <sd:description>Photo Galery presents a set of images, and their thumb nails.</sd:description>
   <sd:version>1.0</sd:version>
   
   <sd:properties>
      <sd:automaticallyLinkSlideToFullSizedImage>true</sd:automaticallyLinkSlideToFullSizedImage>
      <sd:effectDuration>1500</sd:effectDuration>
      <sd:firstSlide>0</sd:firstSlide>
      <sd:galeryLink>http://www.tourism-costarica.com</sd:galeryLink>
      <sd:height>300</sd:height>
      <sd:imageFolderUri>Content/Album</sd:imageFolderUri>
      <sd:showController>true</sd:showController>
      <sd:showImageCaptions>true</sd:showImageCaptions>
      <sd:showSlidesRandom>false</sd:showSlidesRandom>
      <sd:showThumbnails>true</sd:showThumbnails>
      <sd:skipTransition>WhenPaused | OnStart</sd:skipTransition>
      <sd:slideChangeDelay>3000</sd:slideChangeDelay>
      <sd:startPaused>true</sd:startPaused>
      <sd:thumbnailFileNameRule>[/(\.[^\.]+)$/, '_thumb$1']</sd:thumbnailFileNameRule>
      <sd:width>450</sd:width>
   </sd:properties>
</sd:photoGaleryWidgetDefinition>
