=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/PhotoGalery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:pg="http://www.processpuzzle.com/PhotoGalery"
  targetNamespace="http://www.processpuzzle.com/PhotoGalery" 
  elementFormDefault="qualified">

  <xs:element name="photoGalery">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pg:name"/>
        <xs:element ref="pg:description"/>
        <xs:element ref="pg:images"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="images">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="pg:image"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pg:uri"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="pg:caption"/>
          <xs:element ref="pg:link"/>
        </xs:sequence>
        <xs:element ref="pg:thumbnailUri"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="uri" type="xs:NCName"/>
  <xs:element name="caption" type="xs:NCName"/>
  <xs:element name="link" type="xs:anyURI"/>
  <xs:element name="thumbnailUri" type="xs:NCName"/>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/PhotoGaleryWidget/PhotoGaleryData.xml
<?xml version="1.0" encoding="UTF-8"?>
<pg:photoGalery 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://www.w3.org/1999/xhtml"
   xmlns:pg="http://www.processpuzzle.com/PhotoGalery" 
   xsi:schemaLocation="http://www.processpuzzle.com/PhotoGalery http://processpuzzle.com/Schemas/PhotoGalery.xsd">
   
   <pg:name>Pura Vida Costa Rica</pg:name>
   <pg:description>Photos from Costa Rica.</pg:description>
   <pg:images>
      <pg:image>
         <pg:uri>IMAG0337.jpg</pg:uri>
         <pg:caption>PhotoGalery.tabacon</pg:caption>
         <pg:link>http://www.tabacon.com/</pg:link>
         <pg:thumbnailUri>IMAG0337_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>IMAG0339.jpg</pg:uri>
         <pg:caption>PhotoGalery.baldi</pg:caption>
         <pg:link>http://www.arenal.net/hotel/baldi-hotel/index.html</pg:link>
         <pg:thumbnailUri>IMAG0339_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0008.JPG</pg:uri>
         <pg:thumbnailUri>SANY0008_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0012.JPG</pg:uri>
         <pg:thumbnailUri>SANY0012_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0022.JPG</pg:uri>
         <pg:thumbnailUri>SANY0022_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0042.JPG</pg:uri>
         <pg:thumbnailUri>SANY0042_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0058.JPG</pg:uri>
         <pg:thumbnailUri>SANY0058_thumb.jpg</pg:thumbnailUri>
      </pg:image>
      <pg:image>
         <pg:uri>SANY0071.JPG</pg:uri>
         <pg:thumbnailUri>SANY0071_thumb.jpg</pg:thumbnailUri>
      </pg:image>
   </pg:images>
</pg:photoGalery>
