=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/ResourceBundle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:tns="http://www.processpuzzle.com/ResourceBundle">

	<element name="Resources">
		<complexType>
			<sequence>
				<element name="Resource" type="tns:Resource" minOccurs="0" maxOccurs="unbounded"></element>
				<element name="Language" type="tns:Language" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="Resource">
		<simpleContent>
			<extension base="string">
				<attribute name="key" type="token" use="required"></attribute>
				<attribute name="type" type="tns:ResourceType" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<attribute name="key" type="token"></attribute>

	<attribute name="type" type="string"></attribute>

	<simpleType name="ResourceType">
		<restriction base="token">
			<enumeration value="String"></enumeration>
			<enumeration value="File"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="Language">
		<sequence>
			<element name="Resource" type="tns:Resource" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="Country" type="tns:Country" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="tns:LanguageCode" use="required"></attribute>
	</complexType>

	<simpleType name="LanguageCode">
		<restriction base="language">
			<enumeration value="cz"></enumeration>
			<enumeration value="de"></enumeration>
			<enumeration value="dn"></enumeration>
			<enumeration value="en"></enumeration>
			<enumeration value="es"></enumeration>
			<enumeration value="fr"></enumeration>
			<enumeration value="hu"></enumeration>
			<enumeration value="it"></enumeration>
			<enumeration value="pl"></enumeration>
			<enumeration value="pt"></enumeration>
			<enumeration value="ro"></enumeration>
			<enumeration value="sk"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="CountryCode">
		<restriction base="token">
			<enumeration value="HU"></enumeration>
			<enumeration value="US"></enumeration>
			<enumeration value="GB"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="Country">
		<sequence>
			<element name="Resource" type="tns:Resource" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" type="tns:CountryCode" use="required"></attribute>
	</complexType>

</schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Configuration/ConsoleInternationalization.xml
<?xml version="1.0" encoding="UTF-8"?>
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">
    <Resource key="ConsoleTabs.properties" type="String">Properties</Resource>
    <Resource key="ConsoleTabs.comments" type="String">Comments</Resource>
    <Resource key="ConsoleTabs.todo" type="String">To Do</Resource>
    <Resource key="ConsoleTabs.Print" type="String">Print</Resource>
    <Resource key="ConsoleTabs.Close" type="String">Close</Resource>
  </Language>
  
  <Language name="hu">
    <Resource key="ConsoleTabs.properties" type="String">Tulajdonságok</Resource>
    <Resource key="ConsoleTabs.comments" type="String">Megjegyzések</Resource>
    <Resource key="ConsoleTabs.todo" type="String">Saját feladatok</Resource>
    <Resource key="ConsoleTabs.Print" type="String">Nyomtat</Resource>
    <Resource key="ConsoleTabs.Close" type="String">Bezár</Resource>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/WidgetExamples/WidgetExamplesInternationalization_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file contains internalization resources for Desktop Configurator. -->
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">  
    <Resource key="HierarchicalMenuWidgetDocument.exampleDescription" type="String">description</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.introduction" type="String">introduction</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.subTitle" type="String">Hierarhical Menu Widget</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.title" type="String">User Interface Widget</Resource>
    
    <Resource key="MenuExample.mainItemOne" type="String">Main Item One</Resource>
    <Resource key="MenuExample.mainItemTwo" type="String">Main Item Two</Resource>
    <Resource key="MenuExample.mainItemThree" type="String">Main Item Three</Resource>
    <Resource key="MenuExample.itemOne" type="String">Menu Item One</Resource>
    <Resource key="MenuExample.itemTwo" type="String">Menu Item Two</Resource>
    <Resource key="MenuExample.itemThree" type="String">Menu Item Three</Resource>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/Source/Internationalization/TestResources.xml
<?xml version="1.0" encoding="UTF-8"?>
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Resource key="CloseActiveDocumentCommand" type="String">Close</Resource>
  <Resource key="Print" type="String">Print</Resource>
  <Resource key="Save" type="String">Save</Resource>
  <Resource key="Cancel" type="String">Cancel</Resource>
  <Resource key="ShowEditSelectedDocument" type="String">Show document</Resource>
  <Resource key="CreateNewDocument" type="String">Create new document</Resource>
  <Resource key="DeleteSelectedDocument" type="String">Delete document</Resource>

  <Resource key="res_1" type="String">Resource one</Resource>
  <Language name="en">
    <Resource key="res_2" type="String">Resource two</Resource>
  </Language>
  <Language name="hu">
    <Resource key="Print" type="String">Nyomtatás</Resource>
    <Resource key="Save" type="String">Mentés</Resource>
    <Resource key="Cancel" type="String">Mégsem</Resource>
    <Resource key="res_3" type="String">Erőforrás három</Resource>
    <Country name="HU">
      <Resource key="res_4" type="String">Erőforrás négy</Resource>
    </Country>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/SmartDocument/DocumentInternationalization.xml
<?xml version="1.0" encoding="UTF-8"?>
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">
    <Resource key="SmartDocument.headerText" type="String">Sample Smart Document</Resource>
    <Resource key="SmartDocument.itemsTitle" type="String">News</Resource>
    <Resource key="SmartDocument.copyright" type="String">Copyright IT Codex Llc.</Resource>
    <Resource key="SmartDocument.addresses" type="String">Addresses:</Resource>
    <Resource key="DynamicDocument.RSS.link" type="String">link: </Resource>
    <Resource key="DynamicDocument.RSS.description" type="String">description: </Resource>
    <Resource key="DynamicDocument.RSS.language" type="String">language: </Resource>
    <Resource key="DynamicDocument.RSS.pubDate" type="String">publicated: </Resource>
    <Resource key="DynamicDocument.RSS.lastBuildDate" type="String">genarated: </Resource>
    <Resource key="DynamicDocument.RSS.docs" type="String">url: </Resource>
    <Resource key="DynamicDocument.RSS.generator" type="String">generator: </Resource>
    <Resource key="DynamicDocument.RSS.managingEditor" type="String">managing editor: </Resource>
    <Resource key="DynamicDocument.RSS.webMaster" type="String">webmaster: </Resource>
  </Language>

  <Language name="hu">
    <Resource key="SmartDocument.headerText" type="String">Okos dokumentum</Resource>
    <Resource key="SmartDocument.itemsTitle" type="String">Hírek</Resource>
    <Resource key="SmartDocument.copyright" type="String">Minden jog fenntartva, IT Kódex Kft.</Resource>
    <Resource key="SmartDocument.addresses" type="String">Címek:</Resource>
    <Resource key="DynamicDocument.RSS.link" type="String">hivatkozás: </Resource>
    <Resource key="DynamicDocument.RSS.description" type="String">leírás: </Resource>
    <Resource key="DynamicDocument.RSS.language" type="String">nyelv: </Resource>
    <Resource key="DynamicDocument.RSS.pubDate" type="String">publikálva: </Resource>
    <Resource key="DynamicDocument.RSS.lastBuildDate" type="String">generálva: </Resource>
    <Resource key="DynamicDocument.RSS.docs" type="String">cím: </Resource>
    <Resource key="DynamicDocument.RSS.generator" type="String">generátor: </Resource>
    <Resource key="DynamicDocument.RSS.managingEditor" type="String">főszerkesztő: </Resource>
    <Resource key="DynamicDocument.RSS.webMaster" type="String">webmester: </Resource>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/Source/ToolBarWidget/ToolBarInternationalization.xml
<?xml version="1.0" encoding="UTF-8"?>
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">
    <Resource key="ToolBarWidget.alignCenter" type="String">Center</Resource>
    <Resource key="ToolBarWidget.alignJustify" type="String">Justify</Resource>
    <Resource key="ToolBarWidget.alignLeft" type="String">Left</Resource>
    <Resource key="ToolBarWidget.alignRight" type="String">Right</Resource>
  </Language>
  
  <Language name="hu">
    <Resource key="ToolBarWidget.alignCenter" type="String">Középre</Resource>
    <Resource key="ToolBarWidget.alignJustify" type="String">Sorkizárt</Resource>
    <Resource key="ToolBarWidget.alignLeft" type="String">Balra</Resource>
    <Resource key="ToolBarWidget.alignRight" type="String">Jobbra</Resource>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/WidgetExamples/WidgetExamplesInternationalization_hu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file contains internalization resources for Desktop Configurator. -->
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="hu">
    <Resource key="DiagramWidget.Annotation.text" type="String">Ez egy megjegyzés, magyarázó szöveg a digramhoz.</Resource>
    <Resource key="DiagramWidget.ExampleClassOne.name" type="String">Diagram alakzat</Resource>
    <Resource key="DiagramWidget.ExampleClassOne.Attributes.canvas" type="String">vászon</Resource>
    <Resource key="DiagramWidget.ExampleClassOne.Operations.construct" type="String">felépít</Resource>
    <Resource key="DiagramWidget.ExampleClassOne.Operations.destroy" type="String">lebont</Resource>
    <Resource key="DiagramWidget.ExampleClassOne.Operations.draw" type="String">megrajzol</Resource>
    <Resource key="DiagramWidget.ExampleClassTwo.name" type="String">Osztály alakzat</Resource>
    <Resource key="DiagramWidget.ExampleClassTwo.Attributes.attributes" type="String">tulajdonságok</Resource>
    <Resource key="DiagramWidget.ExampleClassTwo.Attributes.operations" type="String">műveletek</Resource>
    <Resource key="DiagramWidget.ExampleClassTwo.Operations.drawAttributes" type="String">tulajdonságokat megrajzol</Resource>
    <Resource key="DiagramWidget.ExampleClassTwo.Operations.drawOperations" type="String">műveleteket megrajzol</Resource>
    
    <Resource key="HierarchicalMenuWidgetDocument.exampleDescription" type="String">leírás</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.introduction" type="String">bevezetés</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.subTitle" type="String">Hierarhikus menu</Resource>
    <Resource key="HierarchicalMenuWidgetDocument.title" type="String">Felhasználói komponens</Resource>
    
    <Resource key="MenuExample.mainItemOne" type="String">Fő menü egy</Resource>
    <Resource key="MenuExample.mainItemTwo" type="String">Fő menü kettő</Resource>
    <Resource key="MenuExample.mainItemThree" type="String">Fő menü három</Resource>
    <Resource key="MenuExample.itemOne" type="String">Menü elem egy</Resource>
    <Resource key="MenuExample.itemTwo" type="String">Menü elem kettő</Resource>
    <Resource key="MenuExample.itemThree" type="String">Menü elem három</Resource>
    
    <Resource key="TreeWidget.Branch1" type="String">Mappa egy</Resource>
    <Resource key="TreeWidget.Branch1-1" type="String">Almappa egy</Resource>
    <Resource key="TreeWidget.Branch2" type="String">Mappa kettő</Resource>
    <Resource key="TreeWidget.Document1" type="String">Dokumentum egy</Resource>
    <Resource key="TreeWidget.Document2" type="String">Dokumentum kettő</Resource>
    <Resource key="TreeWidget.Document3" type="String">Dokumentum három</Resource>
    <Resource key="TreeWidget.Document4" type="String">Dokumnetum négy</Resource>
    <Resource key="TreeWidget.Document5" type="String">Dokumentum öt</Resource>
    <Resource key="TreeWidget.Document6" type="String">Dokumentum hat</Resource>
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Configuration/DesktopInternationalization_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file contains internalization resources for Desktop Configurator. -->
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">
    <Resource key="DesktopConfigurator.desktopTitle" type="String">ProcessPuzzle</Resource>
    <Resource key="DesktopConfigurator.desktopSubTitle" type="String">Workflow and Content Management Business Platform</Resource>
    <Resource key="DesktopConfigurator.navigationBar" type="String">Navigation Bar</Resource>
    <Resource key="DesktopConfigurator.footerText" type="String">Powered by ProcessPuzzle - Copyright 2005-2011, IT Codex Llc.</Resource>
    <Resource key="DesktopConfigurator.Panel.contentBrowserTitle" type="String">Content Browser</Resource>
    <Resource key="DesktopConfigurator.Panel.documentsTitle" type="String">Documents</Resource>
    <Resource key="DesktopConfigurator.Panel.consoleTitle" type="String">Console</Resource>
    <Resource key="DesktopConfigurator.Panel.menusTitle" type="String">Menus</Resource>
    <Resource key="DesktopConfigurator.Panel.tipsTitle" type="String">Tips</Resource>
    <Resource key="DesktopConfigurator.Panel.whoIsIn" type="String">Who is in?</Resource>

    <Resource key="HierarchicalMenuWidget.documentExamples" type="String">Smart Document</Resource>
    <Resource key="HierarchicalMenuWidget.documentExamples.htmlContent" type="String">HTML Content</Resource>
    <Resource key="HierarchicalMenuWidget.documentExamples.staticDocument" type="String">Static Document</Resource>
    <Resource key="HierarchicalMenuWidget.documentExamples.dynamicDocument" type="String">Dynamic Document</Resource>
    <Resource key="HierarchicalMenuWidget.documentExamples.photoAlbum" type="String">Photo Album</Resource>
    <Resource key="HierarchicalMenuWidget.documentExamples.videoAlbum" type="String">Video Album</Resource>

    <Resource key="HierarchicalMenuWidget.administration" type="String">Administration</Resource>
    <Resource key="HierarchicalMenuWidget.administration.users" type="String">Users</Resource>
    
    <Resource key="LanguageSelectorWidget.en" type="String">English</Resource>
    <Resource key="LanguageSelectorWidget.hu" type="String">Hungarian</Resource>
    <Resource key="LanguageSelectorWidget.select" type="String">Choose language:</Resource>

    <Resource key="SkinSelectorWidget.select" type="String">Choose skin:</Resource>
    
    <Resource key="DocumentComments.introduction" type="String">Comments of the active document.</Resource>
    <Resource key="DocumentComments.title" type="String">Comments</Resource>
    
    <Resource key="DocumentEditorToolBar.alignCenter" type="String">Center</Resource>
    <Resource key="DocumentEditorToolBar.alignJustify" type="String">Justify</Resource>
    <Resource key="DocumentEditorToolBar.alignLeft" type="String">Left</Resource>
    <Resource key="DocumentEditorToolBar.alignRight" type="String">Right</Resource>
    
    <Resource key="DocumentProperties.introduction" type="String">Properties of the active document.</Resource>
    <Resource key="DocumentProperties.title" type="String">Document Properties</Resource>
    <Resource key="DocumentProperties.properties.uri" type="String">uri:</Resource>
    <Resource key="DocumentProperties.properties.title" type="String">title:</Resource>
    <Resource key="DocumentProperties.properties.subject" type="String">subject:</Resource>
    <Resource key="DocumentProperties.properties.created" type="String">created:</Resource>
    <Resource key="DocumentProperties.properties.lastModified" type="String">last modified:</Resource>
    
    <Resource key="DynamicDocument.exampleDescription" type="String">The list below is the content of an RSS.xml content source. As the item is a repeated element, more than one news is displayed.</Resource>
    <Resource key="DynamicDocument.footer" type="String">ProcessPuzzle - Desktop like back-end agnostic browser interface</Resource>
    <Resource key="DynamicDocument.introduction" type="String">This example - SmartDocument - retrieves it's content from content xml file. If specified, recurring content elements are repeated automatically.
    The content elements can be edited, modified. Internationalization happens with selecting different language versions of content xml file.</Resource>
    <Resource key="DynamicDocument.itemsTitle" type="String">News:</Resource>
    <Resource key="DynamicDocument.subTitle" type="String">Smart Document Example</Resource>
    <Resource key="DynamicDocument.title" type="String">Dynamic Document</Resource>
    <Resource key="DynamicDocument.RSS.link" type="String">link: </Resource>
    <Resource key="DynamicDocument.RSS.description" type="String">description: </Resource>
    <Resource key="DynamicDocument.RSS.language" type="String">language: </Resource>
    <Resource key="DynamicDocument.RSS.pubDate" type="String">publicated: </Resource>
    <Resource key="DynamicDocument.RSS.lastBuildDate" type="String">genarated: </Resource>
    <Resource key="DynamicDocument.RSS.docs" type="String">url: </Resource>
    <Resource key="DynamicDocument.RSS.generator" type="String">generator: </Resource>
    <Resource key="DynamicDocument.RSS.managingEditor" type="String">managing editor: </Resource>
    <Resource key="DynamicDocument.RSS.webMaster" type="String">webmaster: </Resource>
    
    <Resource key="StaticDocument.exampleDescription" type="String">All of this document's elements are examples to display static content.</Resource>
    <Resource key="StaticDocument.footer" type="String">ProcessPuzzle - Desktop like back-end agnostic browser interface</Resource>
    <Resource key="StaticDocument.introduction" type="String">This example - SmartDocument - contains only static elements defined in the definition xml. 
    As there is no editable values in this document the definition doesn't refers to any content xml. 
    Text values in the definition xml are automatically translated. This features facilitates of creating document templates.</Resource>
    <Resource key="StaticDocument.subTitle" type="String">Smart Document Example</Resource>
    <Resource key="StaticDocument.title" type="String">Static Document</Resource>
    
    <Resource key="PersonalToDoList.introduction" type="String">To Do list of the logged in user.</Resource>
    <Resource key="PersonalToDoList.title" type="String">Personal To Do List</Resource>
    
    <Resource key="PhotoGaleryDocument.title" type="String">Dokumentum beépülő modullal</Resource>
    <Resource key="PhotoGaleryDocument.introduction" type="String">Egy okos dokumentumba tetszőleges számú modul építhető be. A beépülő modulok többnyire speciális módon jelenítenek meg tartamat.</Resource>
    <Resource key="PhotoGaleryDocument.exampleDescription" type="String">A lenti példa egy slide show modul bepítését szemlélteti.</Resource>
    <Resource key="PhotoGaleryDocument.footer" type="String">ProcessPuzzle - Windows szerű, háttér rendszer független, böngészős felhasználói felület</Resource>
    <Resource key="PhotoGaleryDocument.subTitle" type="String">Okos dokumentum példa</Resource>
    
  </Language>
</pp:Resources>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/Source/SmartDocument/DocumentInternationalization.xml
<?xml version="1.0" encoding="UTF-8"?>
<pp:Resources 
	xmlns:pp="http://www.processpuzzle.com/ResourceBundle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ResourceBundle http://www.processpuzzle.com/Schemas/ResourceBundle.xsd ">

  <Language name="en">
    <Resource key="SmartDocument.headerText" type="String">Sample Smart Document</Resource>
    <Resource key="SmartDocument.itemsTitle" type="String">Items</Resource>
    <Resource key="SmartDocument.copyright" type="String">Copyright IT Codex Llc.</Resource>
  </Language>

  <Language name="hu">
    <Resource key="SmartDocument.headerText" type="String">Okos dokumentum</Resource>
    <Resource key="SmartDocument.itemsTitle" type="String">Element</Resource>
    <Resource key="SmartDocument.copyright" type="String">Minden jog fenntartva, IT Kódex Kft.</Resource>
  </Language>
</pp:Resources>
