=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/Schemas/SmartDocument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified">
  <xs:element name="smartDocumentDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="version"/>
        <xs:element ref="documentResources"/>
        <xs:element ref="documentHeader"/>
        <xs:element ref="documentBody"/>
        <xs:element ref="documentFooter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="version" type="xs:decimal"/>

  <xs:element name="documentResources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="styleSheets"/>
        <xs:element ref="images"/>
        <xs:element ref="javascripts"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="styleSheets">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="styleSheet" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="styleSheet" type="xs:string"/>

  <xs:element name="images">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="image" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="image">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="optional" type="xs:NCName"/>
      <xs:attribute name="title" use="optional" type="xs:NCName"/>
	</xs:complexType>
  </xs:element>

  <xs:element name="javascripts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="javascript" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="javascript" type="xs:string"/>

  <xs:element name="documentHeader">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="compositeElement">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
          <xs:attribute name="tag" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="documentBody">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="compositeElement">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
          <xs:attribute name="tag" use="optional" type="xs:NCName"/>
          <xs:attribute name="bind" use="optional" type="xs:string"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="documentFooter">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="compositeElement">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
          <xs:attribute name="tag" use="optional" type="xs:NCName"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="compositeElement">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="compositeElement"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="compositeElement">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="compositeElement"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
      </xs:choice>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="tag" use="required" type="xs:NCName"/>
      <xs:attribute name="bind" use="optional" type="xs:string"/>
      <xs:attribute name="minOccures" use="optional" type="xs:NCName"/>
      <xs:attribute name="maxOccures" use="optional" type="xs:NCName"/>
    </xs:complexType>
</xs:element>
  
  <xs:element name="element">
    <xs:complexType mixed="true">
      <xs:attribute name="bind" use="optional" type="xs:string"/>
      <xs:attribute name="elementStyle" use="optional" type="xs:NCName"/>
      <xs:attribute name="href" type="xs:anyURI"/>
      <xs:attribute name="name" use="optional" type="xs:NCName"/>
      <xs:attribute name="tag" use="optional" type="xs:NCName"/>
      <xs:attribute name="minOccures" use="optional" type="xs:NCName"/>
      <xs:attribute name="maxOccures" use="optional" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/System/DocumentCommentsDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/SmartDocument.xsd">
   
   <sd:name>Comments Document</sd:name>
   <sd:description>Shows comments of associated with the selected content.</sd:description>
   <sd:version>0.5</sd:version>
   
   <sd:resources>
      <sd:styleSheets></sd:styleSheets>
      <sd:images></sd:images>
      <sd:javaScripts></sd:javaScripts>
   </sd:resources>

   <sd:documentHeader tag="div" id="commentsHeader">
      <sd:compositeElement tag="div" id="headerWrapper">
         <sd:element tag="h3">DocumentComments.title</sd:element>
      </sd:compositeElement>
   </sd:documentHeader>
   
   <sd:documentBody tag="div" id="commentsBody">
      <sd:element tag="p">DocumentComments.introduction</sd:element>
   </sd:documentBody>   
</sd:smartDocumentDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/JavaScript/ObjectTests/Desktop/ErroneousDocumentDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:noNamespaceSchemaLocation="http://processpuzzle.com/Schemas/SmartDocument.xsd">
   <name>Test Smart Document</name>
   <description>This configuration supports testing Smart Document.</description>
   <version>0.5</version>
   
   <resources>
      <styleSheets>
         <styleSheet>../SmartDocument/NoneExisting.css</styleSheet>
      </styleSheets>

      <images></images>
      <javaScripts></javaScripts>
   </resources>

   <documentBody tag="div" id="smartDocumentBody">
      <element tag="h4" id="sayHello">Hello World!</element>
   </documentBody>
</smartDocumentDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/System/ErrorDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/SmartDocument.xsd">
   
   <sd:name>Error Page</sd:name>
   <sd:description>Displayed when and error occurred in the front-end.</sd:description>
   <sd:version>0.5</sd:version>
   
   <sd:resources>
      <sd:styleSheets></sd:styleSheets>
      <sd:images></sd:images>
      <sd:javaScripts></sd:javaScripts>
   </sd:resources>

   <sd:documentBody tag="div" id="errorDocumentBody">
      <sd:element tag="h1" id="errorTitle">ErrorDocument.title</sd:element>
      <sd:element tag="p" id="errorTitle">ErrorDocument.introduction</sd:element>
   </sd:documentBody>
   
</sd:smartDocumentDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/VideoGaleryDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:noNamespaceSchemaLocation="file:///e:/GitRepositories/ProcessPuzzleUI/Implementation/WebTier/Schemas/SmartDocument.xsd">
   <name>Photo Galery Document</name>
   <description>Demonstrates Photo Galery widget embeded into a Smart Document.</description>
   <version>0.5</version>
   
   <resources>
      <styleSheets></styleSheets>
      <images></images>
      <javaScripts></javaScripts>
   </resources>

   <documentHeader tag="div" id="photoGaleryDocumentHeader">
      <compositeElement tag="div" id="headerWrapper">
         <element tag="h1">PhotoGaleryDocument.title</element>
      </compositeElement>
   </documentHeader>
   
   <documentBody tag="div" id="smartDocumentBody">
      <element tag="p">PhotoGaleryDocument.paragraph</element>
      <element tag="div" id="PhotoGaleryContainer" elementStyle="slideshow">
      </element>
   </documentBody>
   
   <documentFooter tag="div" id="photoGaleryDocumentFooter">
      <compositeElement tag="div" id="footerWrapper">
         <element tag="h3">PhotoGaleryDocument.footer</element>
      </compositeElement>
   </documentFooter>
</smartDocumentDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/StaticDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<sd:smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:schemaLocation="http://www.processpuzzle.com/SmartDocument http://processpuzzle.com/Schemas/SmartDocument.xsd">
   
   <sd:name>Static Document</sd:name>
   <sd:description>Demonstrates static content of a Smart Document.</sd:description>
   <sd:version>0.5</sd:version>
   
   <sd:resources>
      <sd:styleSheets></sd:styleSheets>
      <sd:images></sd:images>
      <sd:javaScripts></sd:javaScripts>
   </sd:resources>

   <sd:documentHeader tag="div" id="staticDocumentHeader">
      <sd:compositeElement tag="div" id="headerWrapper">
         <sd:element tag="h1">StaticDocument.title</sd:element>
         <sd:element tag="h2">StaticDocument.subTitle</sd:element>
      </sd:compositeElement>
   </sd:documentHeader>
   
   <sd:documentBody tag="div" id="smartDocumentBody">
      <sd:element tag="p">StaticDocument.introduction</sd:element>
      <sd:element tag="p">StaticDocument.exampleDescription</sd:element>
   </sd:documentBody>
   
   <sd:documentFooter tag="div" id="staticDocumentFooter">
      <sd:compositeElement tag="div" id="footerWrapper">
         <sd:element tag="h3">StaticDocument.footer</sd:element>
      </sd:compositeElement>
   </sd:documentFooter>
</sd:smartDocumentDefinition>

=== ZsZs/ProcessPuzzleUI/Implementation/WebTier/WebContent/Content/PersonalToDoListDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<smartDocumentDefinition 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xmlns:pp="http://www.processpuzzle.com" 
   xmlns:sd="http://www.processpuzzle.com/SmartDocument" 
   xsi:noNamespaceSchemaLocation="file:///e:/GitRepositories/ProcessPuzzleUI/Implementation/WebTier/Schemas/SmartDocument.xsd">
   <name>Personal To Do List</name>
   <description>To Do list of the logged in person.</description>
   <version>0.5</version>
   
   <resources>
      <styleSheets></styleSheets>
      <images></images>
      <javaScripts></javaScripts>
   </resources>

   <documentHeader tag="div" id="toDoListHeader">
      <compositeElement tag="div" id="headerWrapper">
         <element tag="h3">PersonalToDoList.title</element>
      </compositeElement>
   </documentHeader>
   
   <documentBody tag="div" id="toDoListBody">
      <element tag="p">PersonalToDoList.introduction</element>
   </documentBody>   
</smartDocumentDefinition>
